/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  gettingStartedSidebar: [
    'getting-started/index',
    {
      type: 'category',
      label: '认识潮汐栈',
      collapsed: false,
      items: ['overview', 'getting-started/roles-and-scenarios'],
    },
    {
      type: 'category',
      label: '开始搭建',
      collapsed: false,
      items: [
        'getting-started/environment-setup',
        'getting-started/install-develop-platform',
        'getting-started/create-first-application',
        'getting-started/first-business-feature',
      ],
    },
  ],
  lowCodeSidebar: [
    'low-code/index',
    {
      type: 'category',
      label: '交付路径',
      collapsed: false,
      items: [
        'low-code/overview',
        'low-code/from-requirement-to-delivery',
        'low-code/development-platform-menu-guide',
      ],
    },
    {
      type: 'category',
      label: '对象与页面',
      collapsed: false,
      items: [
        'guide/tutorial/apps/index',
        'guide/tutorial/business-model/index',
        'guide/tutorial/business-model/develop-business-model/index',
        'guide/tutorial/arrange-modules/index',
        'low-code/page-delivery-with-dynamic-forms-and-ui-schema',
        'low-code/forms-attachments-and-documents',
        'guide/module/statistics-analysis/index',
      ],
    },
    {
      type: 'category',
      label: '规则与流程',
      collapsed: false,
      items: [
        'low-code/workflow-rules-and-automation',
        'guide/module/approval-workflow/index',
        'guide/tutorial/logicflow/index',
        'guide/tutorial/expression/index',
        'guide/tutorial/script/index',
      ],
    },
    {
      type: 'category',
      label: '组织、权限与通知',
      collapsed: false,
      items: [
        'low-code/organization-permissions-configuration-and-notification',
        'guide/module/organization/index',
        'guide/module/rbac/index',
        'guide/tutorial/dict/index',
        'guide/tutorial/configuration/index',
        'guide/tutorial/notification/index',
      ],
    },
    {
      type: 'category',
      label: '集成与自动化',
      collapsed: false,
      items: [
        'low-code/integration-and-scheduled-automation',
        'low-code/development-platform-menus/datasource',
        'low-code/development-platform-menus/backend-api',
        'low-code/development-platform-menus/external-api',
        'low-code/development-platform-menus/scheduled-task',
        'low-code/development-platform-menus/message-queue',
      ],
    },
    {
      type: 'category',
      label: '发布与运行',
      collapsed: false,
      items: [
        'low-code/development-platform-menus/version-management',
        'low-code/development-platform-menus/runtime-instance',
      ],
    },
    {
      type: 'category',
      label: '开发平台菜单参考',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'low-code/development-platform-menus' }],
    },
    {
      type: 'category',
      label: '模块操作参考',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'guide/module' }],
    },
    {
      type: 'category',
      label: '教程参考',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'guide/tutorial' }],
    },
  ],
  fusionDevelopmentSidebar: [
    'fusion-development/index',
    {
      type: 'category',
      label: '决策与协同',
      collapsed: false,
      items: [
        'fusion-development/overview',
        'fusion-development/when-to-use-code',
        'fusion-development/extension-points',
        'fusion-development/high-low-code-collaboration',
        'guide/advance/index',
      ],
    },
    {
      type: 'category',
      label: '前端扩展',
      items: [
        'fusion-development/frontend-extension-paths',
        'fusion-development/workbench-widgets-and-component-libraries',
        'guide/advance/extend-frontend/index',
        'guide/advance/amis-reference/index',
        'guide/advance/extend-frontend/application-transformation',
        'guide/advance/extend-frontend/micro-app/index',
        'guide/advance/extend-frontend/layout-component/index',
        'guide/advance/extend-frontend/amis-component/index',
      ],
    },
    {
      type: 'category',
      label: '后端扩展',
      items: [
        'fusion-development/backend-extension-packages',
        'fusion-development/development-module-scaffold-and-maven-skeleton',
        'guide/advance/extend-backend/index',
        'guide/advance/extend-backend/extend-field/index',
        'guide/advance/extend-backend/extend-expression/index',
        'guide/advance/extend-backend/extend-script/index',
        'guide/advance/extend-backend/extend-logicflow/index',
      ],
    },
    {
      type: 'category',
      label: '集成与认证',
      items: [
        'fusion-development/integration-automation-and-realtime',
        'fusion-development/custom-login-page-and-auth-integration',
        'guide/advance/extend-frontend/micro-app/custom-login-integration',
        'fusion-development/ad-domain-auth-adaptation-guide',
      ],
    },
    {
      type: 'category',
      label: '安全与平台治理',
      items: [
        'fusion-development/development-platform-support-capabilities',
        'fusion-development/authority-subject-and-access-control-design',
        'guide/advance/authority-and-access-control',
      ],
    },
  ],
  operationsSidebar: [
    'operations/index',
    {
      type: 'category',
      label: '部署准备',
      collapsed: false,
      items: [
        'operations/deployment-architecture',
        'operations/environment-requirements',
        'operations/installation-and-initialization',
      ],
    },
    {
      type: 'category',
      label: '发布与升级',
      collapsed: false,
      items: [
        'operations/application-release-and-rollback',
        'operations/release-upgrade-and-rollback',
      ],
    },
    {
      type: 'category',
      label: '专项运行链路',
      collapsed: false,
      items: [
        'operations/runtime-capability-maintenance',
        'operations/task-message-and-realtime-link-maintenance',
        'operations/business-logs-and-audit-traceability',
      ],
    },
    {
      type: 'category',
      label: '监控、备份与排障',
      collapsed: false,
      items: [
        'operations/backup-monitoring-and-troubleshooting',
      ],
    },
  ],
  conceptsSidebar: [{ type: 'autogenerated', dirName: 'concepts' }],
  aiSidebar: [
    'ai/index',
    'ai/terminology',
    'ai/routing-hints',
    'ai/task-recipes',
    'ai/reference-sources',
  ],
  referenceSidebar: [
    'reference/index',
    'reference/platform-capability-map',
    'reference/jsonschema/index',
    { type: 'autogenerated', dirName: 'api' },
    {
      type: 'category',
      label: '常见问题',
      collapsed: false,
      items: ['faq/index', 'faq/backend', 'faq/frontend', 'faq/operations'],
    },
  ],
}

export default sidebars
